Translation/image converter tool pt translation
veler/DevToys pull request #283
Opened 2022-01-27 19:27 UTC by Joaolfelicio

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [x] Internationalization and localization
- [ ] Other (please describe):

## What is the new behavior?

Add pt-pt resw file for the Image Converter tool

## Quality check

Before creating this PR, have you:

- [x] Followed the code style guideline as described in [CONTRIBUTING.md](https://github.com/veler/DevToys/blob/main/CONTRIBUTING.md)
- [x] Verified that the change work in Release build configuration
- [x] Checked all unit tests pass

2022-01-27 20:51 UTC, esibruti requested changes
Olá @Joaolfelicio, deixei umas sugestões de alteração. Algumas palavras que utilizastes do pt-BR em vez do pt-PT. De resto, está tudo bom.

2022-01-27 20:51 UTC, esibruti commented on src/dev/impl/DevToys/Strings/pt-PT/ImageConverter.resw
> +    <comment>{0} é um número decimal que representa um tamanho de arquivo. {1} é uma unidade, como Bytes, KB, MB, GB, TB</comment>
Em português de Portugal, em vez de arquivo é ficheiro

2022-01-27 20:51 UTC, esibruti commented on src/dev/impl/DevToys/Strings/pt-PT/ImageConverter.resw
> +    <value>Apenas arquivos .png, .jpg e .jpeg podem ser usados.</value>
arquivos -> ficheiros

2022-01-27 20:51 UTC, esibruti commented on src/dev/impl/DevToys/Strings/pt-PT/ImageConverter.resw
> +    <value>Selecione o formato de arquivo convertido</value>
arquivo -> ficheiro

2022-01-27 20:51 UTC, esibruti commented on src/dev/impl/DevToys/Strings/pt-PT/ImageConverter.resw
> +    <value>Arraste e largue arquivos de imagem aqui</value>
arquivos -> ficheiros

2022-01-27 20:51 UTC, esibruti commented on src/dev/impl/DevToys/Strings/pt-PT/ImageConverter.resw
> +    <value>Apagar todos</value>
em vez de ser Apagar todos não devia ser Apagar tudo?

2022-01-27 22:56 UTC, Joaolfelicio commented on src/dev/impl/DevToys/Strings/pt-PT/ImageConverter.resw
> +    <value>Arraste e largue arquivos de imagem aqui</value>
`Arraste e largue os ficheiros de imagen aqui` não me soa bem, o que achas/sugeres?

2022-01-27 22:56 UTC, Joaolfelicio commented on src/dev/impl/DevToys/Strings/pt-PT/ImageConverter.resw
> +    <comment>{0} é um número decimal que representa um tamanho de arquivo. {1} é uma unidade, como Bytes, KB, MB, GB, TB</comment>
Verdade! Foi a primeira palavra que me veio à cabeça e ficou, obrigado!

2022-01-27 22:58 UTC, Joaolfelicio commented on src/dev/impl/DevToys/Strings/pt-PT/ImageConverter.resw
> +    <value>Apagar todos</value>
Depende do contexto, mas concordo que neste cenário faz mais sentido  `Apagar tudo`, obrigado!

2022-01-28 09:17 UTC, esibruti commented on src/dev/impl/DevToys/Strings/pt-PT/ImageConverter.resw
> +    <value>Arraste e largue arquivos de imagem aqui</value>
Sendo sincero, não vejo outra frase melhor. Mas caso que encontre uma frase melhor, eu mesmo posso alterar mais tarde

2022-01-28 09:22 UTC, esibruti commented on src/dev/impl/DevToys/Strings/pt-PT/ImageConverter.resw
> +    <value>Arraste e largue arquivos de imagem aqui</value>
Talvez em vez de ser Arraste e largue podia ser Arraste e solte mas o solte é muito à brasileiro por isso mesmo assim, o Arraste e largue não é o pior de todos

2022-01-28 10:39 UTC, Joaolfelicio commented on src/dev/impl/DevToys/Strings/pt-PT/ImageConverter.resw
> +    <value>Arraste e largue arquivos de imagem aqui</value>
Concordo!

2022-01-28 10:43 UTC, esibruti commented on src/dev/impl/DevToys/Strings/pt-PT/ImageConverter.resw
> +    <value>Arraste e largue arquivos de imagem aqui</value>
Por mim, podes marcar tudo como resolvido. De resto, está tudo bem.

2022-01-28 10:49 UTC, Joaolfelicio commented on src/dev/impl/DevToys/Strings/pt-PT/ImageConverter.resw
> +    <value>Arraste e largue arquivos de imagem aqui</value>
Obrigado pela review, vou então marcar como resolvido.

2022-01-28 17:23 UTC, merged