feat: add xml validation tool
veler/DevToys pull request #535
Opened 2022-05-21 13:10 UTC by DotNetInAction

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] UI change (please include screenshot!)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Internationalization and localization
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

## Other information

## Quality check

Before creating this PR, have you:

- [ ] Followed the code style guideline as described in [CONTRIBUTING.md](https://github.com/veler/DevToys/blob/main/CONTRIBUTING.md)
- [ ] Verified that the change work in Release build configuration
- [ ] Checked all unit tests pass

2022-05-27 19:02 UTC, veler commented
Hello,
Thank you very much for this pull request. The cron tool is something that is quite asked by people and I'm sure this will please a lot of customers!

I like the UI overall. A few feedback about it:
The `Next scheduled dates` doesn't scale vertically when the window is being resized. It would be nice to support it like `Regex Tester` tool (you can take example on its implementation ;-) ) 
https://github.com/veler/DevToys/blob/main/src/dev/impl/DevToys/Views/Tools/Text/RegEx/RegExToolPage.xaml

![image](https://user-images.githubusercontent.com/3747805/170773879-57f58fe3-7be9-4cd4-bec7-827b467aaace.png)

Also, the UI feels crowded when we turn on the Compact Overlay (Picture in Picture) mode:
![image](https://user-images.githubusercontent.com/3747805/170773956-297f1577-4e89-4fef-8ee3-b89db962f58a.png)

Perhaps we could hide the options in this scenario? It's something we do in many tools like JSON Formatter. You can use VisualState for this. Here is an example: https://github.com/veler/DevToys/blob/ca0b2f838ce5e5743d904430be0ac323a80ace6f/src/dev/impl/DevToys/Views/Tools/Formatters/JsonFormatter/JsonFormatterToolPage.xaml#L21

Thank you again :) This is a great PR !

2022-05-30 10:28 UTC, DotNetInAction commented
Thank for the review and comments!

I have update my view:

1. Bottom TextBox now fills up the empty space on any size window
2. I have made settings collapsable in compact mode

Let me know what you think!

2022-06-04 07:48 UTC, DotNetInAction commented
Sorry @veler, i thought those two UI changes are the only feedback, unless im being blind :D

2022-06-04 16:04 UTC, veler requested changes
No worries. As I mentioned, I left a few other comments in the code itself. :)

2022-06-15 03:21 UTC, veler commented on src/dev/impl/DevToys/Assets/Icons/Cron.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48">
Where is this SVG coming from? Is there a license we should be aware of?

2022-07-08 05:59 UTC, veler approved these changes
Alright, I addressed all the issues. Thanks again for this contribution. It will be available in the next update. 😁

2022-07-08 05:59 UTC, merged